### PR TITLE
[WIP] Updating Gensim's Word2vec-Keras integration

### PR DESCRIPTION
**Pull request by chinmayapancholi13**
This PR adds support for integration of Keras with Gensim's word2vec model using the `get_embedding_layer` function added to Gensim in [PR#1248](https://github.com/RaRe-Technologies/gensim/pull/1248).

### CODE REVIEW

**Comment by chinmayapancholi13** [comment]
Example usage of the code added in this PR : 

```python
import shorttext

from gensim.models import word2vec as w2v

input_text_file = "word_vectors_training_data.txt"
input_data = w2v.LineSentence(input_text_file)
w2v_model = w2v.Word2Vec(input_data, size=300)
w2v = w2v_model.wv

trainclassdict = shorttext.data.subjectkeywords()
kmodel = shorttext.classifiers.frameworks.CNNWord2Vec(len(trainclassdict.keys()), w2v)
classifier = shorttext.classifiers.VarNNWord2VecClassifier(w2v)
classifier.train(trainclassdict, kmodel)

print(classifier.score('artificial intelligence'))
```

**Output:**
{'mathematics': 0.66653651, 'physics': 0.14110285, 'theology': 0.19236061}

**Comment by chinmayapancholi13** [comment]
@stephenhky I have refactored the code in the [latest commit](https://github.com/stephenhky/PyShortTextCategorization/pull/7/commits/6400793c1d6d2b1df9f51c983ad0be19d6c0b241) by removing some redundant files and classes. I have also added a boolean variable `with_gensim` (with default value `True`) which indicates whether the source of the word-embeddings being used in the Keras model is Gensim's Word2Vec model or not. This boolean variable is used in the classes `CNNWordEmbed` and `VarNNEmbeddedVecClassifier`.

**Comment by stephenhky** [comment]
Thanks for making the codes reusable and backward compatible.

Right now, with this implementation, a trained model is saved without specifying whether use_gensim is True or not. Similarly, when a saved model is being loaded, this information is lacking. But it is important. So somehow there has to be a way to specify.

**Comment by stephenhky** [comment]
Let me authorize this pull request first. But remember the I/O needs to be done.

**Comment by chinmayapancholi13** [comment]
@stephenhky Sure. I'll update the code to include the modifications to the `save`, `load` functions as well.

**Comment by stephenhky** [comment]
Thanks. Also do the same thing for the `DoubleCNNWordEmbed` and `CLSTMWordEmbed` as well.

**Comment by chinmayapancholi13** [comment]
Sure. :)

**Comment by stephenhky** [comment]
What I mean is that, whatever changes you have done to `CNNWordEmbed`, do the similar things to `DoubleCNNWordEmbed` and `CLSTMWordEmbed`.

**Pull request merged**
